# This is a basic workflow to help you get started with Actions

name: XRouter-service-explorer-client-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: # default is 
        # Container registry password
        password: # default is 
        # Container registry server url
        login-server: # default is https://index.docker.io/v1/
